version: '3.9'

services:
  api_server:
    build:
      dockerfile: ./Dockerfile
    command: /usr/local/bin/gunicorn -c gunicorn.conf.py
    expose:
      - 8888
  nginx:
    build: ./nginx
    ports:
      - 8888:8888
    depends_on:
      - api_server
