# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    docker:
      # specify the version you desire here
      # use `-browsers` prefix for selenium tests, e.g. `3.6.1-browsers`
      - image: cimg/python:3.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    resource_class: medium
    
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1.1-dependencies-py310-{{ arch }}-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            # - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate 
            pip install --upgrade pip
            pip install --upgrade wheel
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1.1-dependencies-py310-{{ arch }}-{{ checksum "requirements.txt" }}

      - run:
          name: pylint checks
          command: |
            . venv/bin/activate
            pip install pylint==3.0.2
            python -m pylint ml_rest_fastapi

      - run:
          name: mypy type hint checks
          command: |
            . venv/bin/activate
            pip install mypy==1.6.1
            python -m mypy --pretty --config-file=mypy.ini ml_rest_fastapi

      - run:
          name: black formatter checks
          command: |
            . venv/bin/activate
            pip install black==23.10.1
            python -m black --check ml_rest_fastapi
