name: Build and publish Docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build_and_push_to_registry:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2.1.0

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.2.1

    - name: Login to DockerHub
      uses: docker/login-action@v2.1.0 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v3.2.0
      with:
        push: true
        tags: jgbustos/ml-rest-fastapi:latest
    
    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
